Create memoizer using javaObject inside parfor loop
Using this method seems to prevent errors of type:
Error: MATLAB cannot determine whether "loci" refers to a function or variable.
See Parallel for Loops in MATLAB, "Unambiguous Variable Names".

Caused by:
    Error using distcompdeserialize
    Error: MATLAB cannot determine whether "loci" refers to a function or
    variable.