Upgrade SLF4J to 1.7.2 across the board
This also upgrades log4j to 1.2.17, which is the corresponding version
for that version of SLF4J.

The reason for the upgrade is to improve the behavior of SLF4J in case
there is no logger implementation binding present. Specifically,
starting with SLF4J 1.6, SLF4J defaults to a no-op logger when no
binding is present, rather than throwing NoClassDefFoundError. This is
much nicer for downstream consumers of Bio-Formats, since they do not
need to worry about always specifying an SLF4J binding as a dependency
in addition to Bio-Formats.